[build]
    publish = "public"

[functions]
    directory = "lib/netlify/"
    node_bundler = "esbuild"

[[redirects]]
    from = "/"
    to = "https://github.com/CodeYourFuture/gitbot/"
    status = 302
    [redirects.headers]
        X-From = "Netlify"
